# Use X-Forwarded-*-headers for absolute URL resolution
server:
  forward-headers-strategy: framework
  shutdown: graceful
  port: ${PORT:8080}

spring:
  application:
    name: plantevernjournal-innlesing-api

  cloud:
    gcp:
      core:
        enabled: true
      secretmanager:
        enabled: true

  config:
    import: "sm@"

  profiles:
    active: local

eppo:
  api:
    uri: "https://api.eppo.int/gd/v2"
    token: ${sm@eppo-api-token}

nats:
  url: tls://connect.nats.mattilsynet.io:4222
  creds: ${sm@nats-creds}

# agdir, agrilogg, farmable, jordplan, skifteplan, mattilsynet
fagsystemer: 921893639,924293438,821604702,996063631,878700562,985399077
