### Post plantevernjournal for frø og formeringsmateriale
POST http://localhost:8080/plantevernjournal/innlesing/v1/formeringsmateriale
Content-Type: application/json

{
  "behandledeVekster":  [
    {
      "bbchFase": "05",
      "eppoKode": "SOLTU",
      "partinummer": 2
    },
    {
      "bbchFase": "01",
      "eppoKode": "MMMMM",
      "partinummer": 27
    }
  ],
  "behandler": {
    "etternavn": "Andersen",
    "fornavn": "Grete"
  },
  "behandletDato": "2024-10-18",
  "behandletMengde": {
    "enhet": "KILO_PER_DEKAR",
    "verdi": 55.6
  },
  "behandledeOmraader": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "geometry": {
          "type": "LineString",
          "coordinates": [
            [
              10.993992026,
              60.72196783
            ],
            [
              10.994093671,
              60.722057656
            ]
          ]
        }
      }
    ]
  },
  "bruksomraade": "JORDBRUK",
  "organisasjonsnummerEier": "987654123",
  "organisasjonsnummerSproeyter": "897456875",
  "plantevernmiddel": [
    {
      "dosering": {
        "enhet": "LITER_PER_KILO",
        "verdi": 34
      },
      "registreringsnummer": "12345"
    }
  ]
}

> {%
    client.test("Innlesing av frø og formeringsmateriale gikk bra", function () {
        client.assert(response.status === 201, "Status er ikke 201");
    });

    const id = jsonPath(response.body, '$.id')
    client.global.set("formeringsmaterialeId", id)
%}

### Delete plantevernjournal for frø og formeringsmateriale
DELETE http://localhost:8080/plantevernjournal/innlesing/v1/formeringsmateriale/{{formeringsmaterialeId}}
Content-Type: application/json

> {%
    client.test("Sletting av frø og formeringsmateriale gikk bra", function () {
        client.assert(response.status === 204, "Status er ikke 204");
    });

%}
