### Post plantevernjournal for utendørs bruk
POST http://localhost:8080/plantevernjournal/innlesing/v1/utendoersbruk
Content-Type: application/json

{
  "arealBehandletOmraade": {
    "enhet": "DEKAR",
    "verdi": 65
  },
  "behandledeVekster": [
    {
      "bbchFase": "05",
      "eppokode": "SOLTU",
      "partinummer": 2
    },
    {
      "bbchFase": "01",
      "eppokode": "MMMMM",
      "partinummer": 27
    }
  ],
  "behandler": {
    "etternavn": "Hansen",
    "fornavn": "Tine"
  },
  "behandledeOmraader": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                10.993992026,
                60.72196783
              ],
              [
                10.994093671,
                60.722057656
              ],
              [
                10.994777701,
                60.72187064
              ],
              [
                10.995895613,
                60.721563909
              ],
              [
                10.995797879,
                60.721475104
              ],
              [
                10.995729609,
                60.721414959
              ],
              [
                10.9950005,
                60.721613967
              ],
              [
                10.994943302,
                60.721563805
              ],
              [
                10.994549717,
                60.721671239
              ],
              [
                10.99460847,
                60.721722814
              ],
              [
                10.993925502,
                60.721909185
              ],
              [
                10.993992026,
                60.72196783
              ]
            ]
          ]
        }
      },
      {
        "type": "Feature",
        "geometry": {
          "type": "LineString",
          "coordinates": [
            [
              10.993992026,
              60.72196783
            ],
            [
              10.994093671,
              60.722057656
            ]
          ]
        }
      }
    ]
  },
  "bruksomraade": "JORDBRUK",
  "gaardsnummer": "0505-067-11",
  "organisasjonsnummer": "987654123",
  "plantevernmiddel": [
    {
      "autorisasjonsnummer": "12345",
      "dosering": {
        "enhet": "LITER_PER_KILO",
        "verdi": 34
      }
    }
  ],
  "startTid": "2024-10-18T12:00:00"
}
