### Post plantevernjournal for frø og formeringsmateriale
POST http://localhost:8080/plantevernjournal/innlesing/v1/formeringsmateriale
Content-Type: application/json

{
  "behandledeVekster": {
    "bbchFase": "05",
    "eppoKode": "1SOLTU",
    "partinummer": 2
  },
  "behandletDato": "2024-10-18",
  "behandletMengde": {
    "enhet": "KILO_PER_DEKAR",
    "verdi": 55.6
  },
  "behandletOmraade": {
    "omraade": "Her må vi legge inn noe"
  },
  "bruksomraade": "JORDBRUK",
  "gaardsnummer": "0505-050-12",
  "plantevernmiddel": [
    {
      "autorisasjonsnummer": "12345",
      "dosering": {
        "enhet": "LITER_PER_KILO",
        "verdi": 34
      }
    }
  ]
}

### Post plantevernjournal for innendørs bruk
POST http://localhost:8080/plantevernjournal/innlesing/v1/innendoersbruk
Content-Type: application/json

{
  "behandledeVekster": {
    "bbchFase": "05",
    "eppoKode": "1SOLTU",
    "partinummer": 2
  },
  "behandletDato": "2024-10-18T12:00:00",
  "behandletOmraade": {
    "omraade": "Her må vi legge inn noe"
  },
  "bruksomraade": "JORDBRUK",
  "bygningsnummer": "512",
  "bygningsstoerrelse": {
    "enhet": "KVADRATMETER",
    "verdi": 450
  },
  "gaardsnummer": "0505-067-11",
  "plantevernmiddel": [
    {
      "autorisasjonsnummer": "12345",
      "dosering": {
        "enhet": "LITER_PER_KILO",
        "verdi": 34
      }
    }
  ]
}

### Post plantevernjournal for utendørs bruk
POST http://localhost:8080/plantevernjournal/innlesing/v1/utendoersbruk
Content-Type: application/json

{
  "arealBehandletOmraade": {
    "enhet": "DEKAR",
    "verdi": 65
  },
  "behandledeVekster": {
    "bbchFase": "05",
    "eppoKode": "1SOLTU",
    "partinummer": 2
  },
  "behandletOmraade": {
    "omraade": "Her må vi legge inn noe"
  },
  "bruksomraade": "JORDBRUK",
  "gaardsnummer": "0505-067-11",
  "plantevernmiddel": [
    {
      "autorisasjonsnummer": "12345",
      "dosering": {
        "enhet": "LITER_PER_KILO",
        "verdi": 34
      }
    }
  ],
  "startTid": "2024-10-18T12:00:00"

}
